export const fontFamilies={
    Barriecito: 'Barriecito, cursive',
    BebasNeue: 'Bebas Neue, sans-serif',
    CroissantOne: 'Croissant One, cursive',
    Dela: 'Dela Gothic One, cursive',
    Fuggles: 'Fuggles, cursive',
    Great: 'Great Vibes, cursive',
    Lobster: 'Lobster, cursive',
    Martian: 'Martian Mono, monospace',
    Mooli: 'Mooli, sans-serif',
    Oswald: 'Oswald, sans-serif',
    Pacifico: 'Pacifico, cursive',
    Permanent: 'Permanent Marker, cursive',
    Philosopher: 'Philosopher, sans-serif',
    Poppins: 'Poppins, sans-serif',
    Press: 'Press Start 2P, cursive',
    Raleway: 'Raleway, sans-serif',
    Righteous: 'Righteous, cursive',
    Roboto: 'Roboto, sans-serif',
    Russo: 'Russo One, sans-serif',
    Sacramento: 'Sacramento, cursive',
    Skranji: 'Skranji, cursive',
    Tangerine: 'Tangerine, cursive',
    Tilt: 'Tilt Prism, cursive',
    Tourney: 'Tourney, cursive',
    Wavefont: 'Wavefont, cursive',
    Yeseva: 'Yeseva One, cursive',
}